spring.application.name=posting
spring.profiles.active=dev,maria,jpa
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.pattern.console=%clr(%-5level){green} %clr(%logger.%M\\(\\)){blue}: %msg%n
server.error.whitelabel.enabled=false