SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60;

-- 단일 행 함수 (문자)
SELECT EMPLOYEE_ID, FIRST_NAME, UPPER(FIRST_NAME), LOWER(FIRST_NAME),
    SUBSTR(FIRST_NAME,1,3) AS "3자리",
    INSTR(FIRST_NAME,'E') AS "위치찾기",
    INSTR(FIRST_NAME,'E',5) AS "위치찾기",
    LENGTH(FIRST_NAME) AS "길이",
    REPLACE(FIRST_NAME,'A','AAA') AS "변경",
    TRIM(FIRST_NAME) AS "앞 뒤 공백을 제거",
    TRIM('D' FROM FIRST_NAME) AS "특정 문자 지우기",
    LPAD(EMPLOYEE_ID, 5, '0') AS "좌측으로 채우기",
    RPAD(FIRST_NAME, 9, '*') AS "우측으로 채우기"
FROM EMPLOYEES;

SELECT TRIM('             STEVEN               ')||'*'
FROM DUAL;

SELECT LTRIM('             STEVEN               ')||'*'
FROM DUAL;

SELECT RTRIM('             STEVEN               ')||'*'
FROM DUAL;

-- 단일 행 함수 (숫자)
SELECT ROWNUM, EMPLOYEE_ID, SALARY,
    ROUND(SALARY * 1.08) AS "반올림",
    ROUND(SALARY * 1.08, -2) AS "양수-N까지반올림",
    ROUND(SALARY * 1.08, 1) AS "소수N자리까지반올림",
    TRUNC(SALARY * 1.08) AS "버림"
FROM EMPLOYEES;

-- 단일 행 함수 (날짜)
SELECT EMPLOYEE_ID AS "ID", FIRST_NAME, HIRE_DATE,
    TRUNC(SYSDATE - HIRE_DATE) AS "근무일수",
    TRUNC(MONTHS_BETWEEN(SYSDATE, HIRE_DATE),1) AS "개월수",
    CEIL(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12) AS "년차",
    ADD_MONTHS(HIRE_DATE, 6) AS "입사 6개월 후 일자",
    LAST_DAY(HIRE_DATE) AS "입사한 달의 말일",
    
    TRUNC(HIRE_DATE, 'MM') AS "월 단위 절사", -- 달의 시작일
    ROUND(HIRE_DATE, 'MM') AS "월 단위 반올림",
    EXTRACT(YEAR FROM HIRE_DATE) AS "년도 추출",
    TO_CHAR(HIRE_DATE, 'YYYY') AS "년도 추출2"
FROM EMPLOYEES;

-- 현재 SESSION SETTING 확인
SELECT * FROM NLS_SESSION_PARAMETERS;

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

-- 변환 함수 : TO_CHAR(), TO_NUMBER(), TO_DATE()
SELECT EMPLOYEE_ID,
    HIRE_DATE,
    TO_CHAR(HIRE_DATE, 'YY"년" MM"월" DD"일"'),
    TO_CHAR(HIRE_DATE, 'MON'),
    TO_CHAR(HIRE_DATE, 'DAY'),
    SALARY,
    TO_CHAR(SALARY, '999,999,999,999') AS "포맷",
    TO_CHAR(SALARY, '000,000,000,000') AS "0으로 채우기",
    TO_CHAR(SALARY, 'L999,999,999,999') AS "포맷(원표시)",
    TO_CHAR(SALARY, 'L000,000,000,000') AS "0으로 채우기(원표시)",
    TO_NUMBER('1,234,567','9,999,999') AS "문자->숫자",
    MONTHS_BETWEEN(TO_DATE('06-09/26', 'MM-DD/YY'),HIRE_DATE)
FROM EMPLOYEES;

-- NULL 처리
SELECT FIRST_NAME, SALARY, COMMISSION_PCT,
    SALARY + NVL(COMMISSION_PCT, 0) AS "NULL 인 경우 대체값",
    SALARY + NVL2(COMMISSION_PCT, COMMISSION_PCT - 500, 0) AS "NULL 인 경우 분기 값",
--    NULLIF('NULL 인 경우 대체값', 'NULL 인 경우 분기 값'), -- 다르면 앞에 값, 같으면 NULL
    COALESCE(COMMISSION_PCT, DEPARTMENT_ID, SALARY) AS "NULL이 아닌 최초값"
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL;

---- DECODE문 (= Java의 if) ORACLE 전용
--SELECT EMPLOYEE_ID,
--       JOB_ID,
--       SALARY,
--       DECODE(JOB_ID,
--              'AD_PRES', SALARY * 1.2,
--              'AD_VP',   SALARY * 1.15,
--              'IT_PROG', SALARY * 1.1,
--                         SALARY * 1.05) AS 인상후급여
--FROM   EMPLOYEES
--WHERE  DEPARTMENT_ID IN (90, 60)
--ORDER  BY DEPARTMENT_ID, SALARY DESC;

-- CASE WHEN (= Java의 switch)
-- CASE WHEN 단순 형식 (DECODE와 동일한 기능)
SELECT EMPLOYEE_ID,
       SALARY,
       CASE JOB_ID
         WHEN 'AD_PRES' THEN '임원'
         WHEN 'AD_VP'   THEN '부사장'
         WHEN 'IT_PROG' THEN 'IT개발자'
         ELSE '기타'
       END AS 직무구분,
       CASE
         WHEN JOB_ID LIKE 'AD%' THEN '임원'
         WHEN JOB_ID LIKE 'AD%' THEN '부사장' -- 같은 조건이라면 먼저 오는 값
         WHEN JOB_ID LIKE 'IT%' THEN 'IT개발자'
         ELSE '기타'
       END AS 직무구분
FROM   EMPLOYEES
WHERE  DEPARTMENT_ID IN (90, 60);

-- CASE WHEN 검색 형식 (범위 조건 가능)
SELECT EMPLOYEE_ID,
       SALARY,
       CASE
         WHEN SALARY >= 15000 THEN 'S등급'
         WHEN SALARY >= 10000 THEN 'A등급'
         WHEN SALARY >=  5000 THEN 'B등급'
         ELSE 'C등급'
       END AS 급여등급
FROM   EMPLOYEES
ORDER  BY SALARY DESC;

-- SALARY 10000 이상이면 급여(상), 5000 이상이면 중, 기타 하
SELECT EMPLOYEE_ID AS ID,
    CASE 
        WHEN SALARY >= 10000 THEN '상'
        WHEN SALARY >= 5000 THEN '중'
        ELSE '하'
    END AS "급여등급"
FROM EMPLOYEES
WHERE  DEPARTMENT_ID IN (90, 60)
ORDER BY SALARY DESC;

-- FIRST_NAME 의 길이를 판단해서 10자리 이상'Long', 5자리 이상'Middle', 그 외'Short'
SELECT FIRST_NAME,
    CASE
        WHEN LENGTH(FIRST_NAME) >= 10 THEN 'Long'
        WHEN LENGTH(FIRST_NAME) >= 5 THEN 'Middle'
        ELSE 'Short'
    END AS "이름 길이"
FROM EMPLOYEES
ORDER BY LENGTH(FIRST_NAME) DESC;

-- 그룹함수
-- 집계함수 (NULL 무시)
SELECT COUNT(*), COUNT(DEPARTMENT_ID), COUNT(COMMISSION_PCT),
    SUM(SALARY), AVG(SALARY), MIN(SALARY), MAX(SALARY)
FROM EMPLOYEES;

-- **SELECT 절에 그룹 함수 외 컬럼이 있으면 모두 GROUP BY에 포함**
-- 부서별 급여의 합계와 직원수
SELECT DEPARTMENT_ID, COUNT(*), SUM(SALARY)
FROM EMPLOYEES
GROUP BY ROLLUP(DEPARTMENT_ID) --ROLLUP 전체의 값 출력
ORDER BY 1 NULLS FIRST;

-- 직급별 급여의 합계와 직원수
SELECT JOB_ID, SUM(SALARY), COUNT(*) AS "인원"    --5
FROM EMPLOYEES  --1
WHERE SALARY > 0    --2
GROUP BY JOB_ID     --3
HAVING COUNT(*) >= 5    --4
ORDER BY 3 DESC NULLS LAST; --6

-- 부서별, 직급별 급여의 합계와 직원수
SELECT DEPARTMENT_ID AS "부서ID", 
    CASE GROUPING(JOB_ID)
        WHEN 1 
            THEN 
                CASE GROUPING(DEPARTMENT_ID)
                    WHEN 1 THEN '총합'
                    ELSE '부서별 합계'
                END    
        ELSE JOB_ID
    END AS "JOB_ID",
    SUM(SALARY), COUNT(*),
    GROUPING(DEPARTMENT_ID) AS "부서합", GROUPING(JOB_ID) AS "직무합"
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY ROLLUP(DEPARTMENT_ID, JOB_ID)
ORDER BY 1,2;

-- 부서별 직원 이름 목록을 한줄로
SELECT DEPARTMENT_ID, COUNT(*),
    LISTAGG(FIRST_NAME, ',') WITHIN GROUP (ORDER BY SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- JOIN 두개 이상의 테이블을 연결하는 연산 -> 설계 시 중복을 없애기 위해 정규화 과정 후 조회 시 연결하여 가져온다

-- ORACLE 전용
-- 직원이 부서를 참조, 직원건수만큼 출력
-- 직원 중 부서를 참조하지 않는 경우, 해당 데이터는 제외
SELECT COUNT(*)
FROM EMPLOYEES, DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;
-- ORACLE OUTER JOIN
SELECT COUNT(*)
FROM EMPLOYEES, DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID(+);

-- 범용(ANSI 표준)
SELECT COUNT(*) -- 공통 칼럼은 TABLE.을 사용하면 오류
FROM EMPLOYEES
JOIN DEPARTMENTS
USING (DEPARTMENT_ID);

-- INNER JOIN
SELECT COUNT(*) -- COLUMN의 이름이 동일한 경우 반드시 TABLE.으로 명시
FROM EMPLOYEES
JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

-- OUTER JOIN

-- LEFT JOIN : 기준 테이블은 모두 출력
SELECT EMPLOYEES.EMAIL, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
LEFT JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
ORDER BY DEPARTMENTS.DEPARTMENT_NAME NULLS FIRST;

-- RIGHT JOIN : 참조 테이블 모두 출력
SELECT EMPLOYEES.EMAIL, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
RIGHT JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
ORDER BY EMPLOYEES.EMAIL NULLS FIRST;

-- FULL OUTER JOIN : 모든 테이블 출력
SELECT EMPLOYEES.EMAIL, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
FULL JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
ORDER BY EMPLOYEES.EMAIL NULLS FIRST;



-- 벤더 문법
SELECT EMPLOYEES.FIRST_NAME,
    DEPARTMENTS.DEPARTMENT_NAME,
    LOCATIONS.CITY,
    COUNTRIES.COUNTRY_NAME,
    REGIONS.REGION_NAME
FROM EMPLOYEES, DEPARTMENTS, LOCATIONS, COUNTRIES, REGIONS
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    AND DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
    AND LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
    AND COUNTRIES.REGION_ID = REGIONS.REGION_ID;

-- ANSI 표준 문법
SELECT EMPLOYEES.FIRST_NAME,
    DEPARTMENTS.DEPARTMENT_NAME,
    LOCATIONS.CITY,
    COUNTRIES.COUNTRY_NAME,
    REGIONS.REGION_NAME
FROM EMPLOYEES
JOIN DEPARTMENTS USING(DEPARTMENT_ID)
JOIN LOCATIONS USING(LOCATION_ID)
JOIN COUNTRIES USING(COUNTRY_ID)
JOIN REGIONS USING(REGION_ID);

SELECT EMPLOYEES.FIRST_NAME,
    DEPARTMENTS.DEPARTMENT_NAME,
    LOCATIONS.CITY,
    COUNTRIES.COUNTRY_NAME,
    REGIONS.REGION_NAME
FROM EMPLOYEES
JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
JOIN LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
JOIN COUNTRIES ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
JOIN REGIONS ON COUNTRIES.REGION_ID = REGIONS.REGION_ID;


-- SELF JOIN
SELECT OE.FIRST_NAME || ' ' || OE.LAST_NAME AS "본인 이름", JE.FIRST_NAME || ' ' || JE.LAST_NAME AS "상사"
FROM EMPLOYEES OE
LEFT JOIN EMPLOYEES JE ON OE.MANAGER_ID = JE.EMPLOYEE_ID
ORDER BY OE.EMPLOYEE_ID;



-- 부서별 직원들의 급여 합계
SELECT D.DEPARTMENT_NAME AS "부서명", SUM(E.SALARY) AS "급여 합계", COUNT(*) AS "직원수"
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
HAVING SUM(E.SALARY) > 50000
ORDER BY "급여 합계" DESC;



