spring.application.name=bananaapp
#server.port=8888
#shinhan.api.key=${MY_APIKEY}
spring.profiles.active=dev,maria,jpa,mybatis,jwt,redis
#level : TRACE > DEBUG > INFO > WARN >ERROR
logging.level.root=INFO
#logging.level.com.shinhan.bananaapp=INFO
#logging.level.org.springframework.boot=INFO
logging.level.org.springframework.web=INFO
#logging.level.com.shinhan.bananaapp.mapper=DEBUG
#logging.level.org.springframework.security.web=trace
logging.pattern.console=%clr(%-5level){green} %clr(%logger.%M\\(\\)){blue}: %msg%n
#file.upload-dir=:C:/upload/shinhan/
server.error.whitelabel.enabled=false